CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  firstname VARCHAR(100) NOT NULL,
  lastname  VARCHAR(100) NOT NULL,
  email     VARCHAR(255) NOT NULL,
  phonenumber VARCHAR(50) NOT NULL,
  password  VARCHAR(255) NOT NULL
);
